name: 'codewatchers-assignees'
description: 'Set PR assignees based on a CODEOWNERS file'
author: 'mavtek'
branding: 
  icon: 'users'
  color: 'purple'
inputs:
  github-token:
    required: true
    description: 'Auth token with permissions to label PR '
  codewatchers-filename:
    required: false
    description: 'Filename of codewatchers file.'
    default: 'CODEWATCHERS'
  github-user-mappings:
    required: false
    description: 'Optional list of mappings from codewatchers to github users. Delimited by colon.'
  add-assignees:
    required: false
    description: 'Optional defaults to true, false to note add assignees'
runs:
  using: 'node16'
  main: 'dist/index.js'
