name: Test Codeowners

on:
  push:
    branches-ignore:
      - main
  pull_request:
jobs:
  Build:
    uses: ./.github/workflows/test.yml

  Notification-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Find CODEOWNERS of changed files
        id: codeowners
        uses: ./
        with:
          codewatchers-filename: CODEOWNERS
          github-token: ${{ secrets.GITHUB_TOKEN }}
          add-assignees: false
      - name: Output CODEOWNERS
        run: echo ${{ steps.codeowners.outputs.assignees }}