name: Test Codeowners

on:
#  push:
  #    branches-ignore:
  #      - main
  pull_request:
jobs:
  Notification-Preview:
    runs-on: ubuntu-latest
    environment:
      name: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Find CODEOWNERS of changed files
        id: codeowners
        uses: mavtek/codewatchers@v1
        with:
          codewatchers-filename: CODEOWNERS
          github-token: ${{ secrets.GITHUB_TOKEN }}
          add-assignees: false
      - name: Output CODEOWNERS
        run: echo ${{ steps.codeowners.outputs.add-assignees }}
